import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { makeStyles } from '@material-ui/core/styles'
import TextField from '@material-ui/core/TextField'
import Button from '@material-ui/core/Button'
import Box from '@material-ui/core/Box'
import { useState } from 'react'

const useStyles = makeStyles({
  basic: {
    padding: '20px',
    margin: '10px',
    backgroundColor: 'black',
    color: 'white',
  },
  flexdisplay: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  button: {

  }
})
export default function Home() {

    const [question, setQuestion] = useState(""); 
    const classes = useStyles();

    const handleClick = () =>{
      console.log("you clicked the button");
    }

    const handleSubmit = (e) => {
      alert('An event was submitted: ' + this.state.value)
      e.preventDefault();
    }

  return (
    <div className={styles.container}>
      <div className={styles.overlay}></div>
      <Head>
        <title>Giotto Tarot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Giotto Tarot
        </h1>
        <form onSubmit={handleSubmit} className={classes.flexdisplay}>
          <h2>enter your question below: </h2>
          <TextField className={styles.input} value={question} onChange={(e) => setQuestion(e.target.value)}/>
          <br />
          <Box className={classes.flexdisplay}>
            <Button onClick={handleClick} className={classes.basic}>reveal my fate</Button>
          </Box>
        </form>
      </main>
    </div>
  )
}
